music = {
    "stealth": "https://www.youtube.com/watch?v=U47Tr9BB_wE",
    "march": "https://www.youtube.com/watch?v=Xqeq4b5u_Xw",
    "skyfall": "https://www.youtube.com/watch?v=DeumyOzKqgI&pp=ygUHc2t5ZmFsbA%3D%3D",
    "wolf": "https://www.youtube.com/watch?v=ThCH0U6aJpU&list=PLnrGi_-oOR6wm0Vi-1OsiLiV5ePSPs9oF&index=21",
    "shaky":"https://www.youtube.com/watch?v=sUf2PtEZris",
    "aankhein":"https://www.youtube.com/watch?v=eM8Mjuq4MwQ",
    "aaj se teri":"https://www.youtube.com/watch?v=NFsEqOBG51M",
    "Khaiyaryat":"https://www.youtube.com/watch?v=hoNb6HuNmU0",
    "jhol":"https://www.youtube.com/watch?v=-2RAq5o5pwc",
    "shiddat":"https://www.youtube.com/watch?v=iSo9l950QLo",
    "bulleya":"https://www.youtube.com/watch?v=a9Hxkc9YxGE",
    "zallima":"https://www.youtube.com/watch?v=hhdSyBHuI88",
    "kolaveri":"https://www.youtube.com/watch?v=YR12Z8f1Dh8",
    "sahiba":"https://www.youtube.com/watch?v=n2dVFdqMYGA",
}